meta_product_name: "Billy Mate"
meta_title: "Billy Mate - ton nouveau compagnon pour gérer les factures entre colocataires"
meta_description: "L'application qui t'aide à gérer tes factures entre colocataires"
meta_image: "cover.png" # should exist in `app/assets/images/`
